version: '3.4'

services:

  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: scripty
      POSTGRES_PASSWORD: scripty

  stt:
    image: wilt/scripty-stt:0.1.0-cuda
    environment:
      - MODEL_NAME=ggml-medium.en.bin
      - INSTANCE_COUNT=2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - D:\ai:/models
    ports:
      - 7269:7269

  cache:
    image: redis:7.2.3-alpine
    restart: always

  bot:
    image: wilt/scripty:0.0.8
    ports:
      - 42069:42069
    depends_on:
      - db
      - stt
      - cache
    volumes:
      - ./scripty-config:/config
    environment:
      - RUST_BACKTRACE=1

  monitor:
    image: grafana/loki:2.8.6
    ports:
      - 3100:3100
      - 7946
      - 9095

  dashboard:
    image: grafana/grafana-oss:10.2.2
    restart: unless-stopped
    ports:
      - 3000:3000
