global:
  scrape_interval: 15s

scrape_configs:
  - job_name: scripty
    static_configs:
      - targets:
          - "bot:42069"
  - job_name: redis_exporter
    static_configs:
      - targets:
          - "redis_exporter:9121"
  - job_name: postgres_exporter
    static_configs:
      - targets:
          - "postgres_exporter:9187"
  - job_name: alertmanager
    static_configs:
      - targets:
          - "alertmanager:9093"
  - job_name: loki
    static_configs:
      - targets:
          - "loki:3100"
  - job_name: grafana
    static_configs:
      - targets:
          - "grafana:3000"
