global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: scripty
    static_configs:
      - targets:
          - "bot:42069"
  - job_name: redis_exporter
    static_configs:
      - targets:
          - "redis_exporter:9121"
  - job_name: postgres_exporter
    static_configs:
      - targets:
          - "postgres_exporter:9187"
  - job_name: alertmanager
    static_configs:
      - targets:
          - "alertmanager:9093"
  - job_name: loki
    static_configs:
      - targets:
          - "loki:3100"
  - job_name: grafana
    static_configs:
      - targets:
          - "grafana:3000"
