global:
  scrape_interval: 15s

scrape_configs:
  - job_name: scripty
    static_configs:
      - targets: ["bot:42069"]
  - job_name: redis_exporter
    static_configs:
      - targets: ["redis-exporter:9121"]
