[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Ctarget-cpu=native", "--cfg", "tokio_unstable", "-C", "link-arg=-fuse-ld=mold", "-Zshare-generics=y"]

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = ["-Ctarget-cpu=native", "--cfg", "tokio_unstable", "-C", "link-arg=-fuse-ld=mold", "-Zshare-generics=y"]

[target.x86_64-pc-windows-gnu]
rustflags = ["--cfg", "tokio_unstable"]

[target.x86_64-pc-windows-msvc]
rustflags = ["--cfg", "tokio_unstable"]
